config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "static_pages#home"
  resources :garments, except: [:edit, :update, :destroy]
end


  

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/garment.rb
class Garment < ApplicationRecord
  belongs_to :user

  #validaciones 
  
  validates :name, :brand, :size, :date_of_purchase, presence: true
  validates :size, inclusion: { in: %w[S M L] }
  validate :date_of_purchase_cannot_be_in_the_future

  private

  def date_of_purchase_cannot_be_in_the_future
    errors.add(:date_of_purchase, "can't be in the future") if date_of_purchase && date_of_purchase > Date.today
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :garments
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/garments_controller.rb
class GarmentsController < ApplicationController
    before_action :authenticate_user!
  
    def index
      @garments = current_user.garments
    end
  
    def show
      @garment = current_user.garments.find(params[:id])
    end
  
    def new
      @garment = current_user.garments.build
    end
  
    def create
      @garment = current_user.garments.build(garment_params)
      if @garment.save
        redirect_to garments_path, notice: 'Garment was successfully created.'
      else
        render :new
      end
    end
  
    private
  
    def garment_params
      params.require(:garment).permit(:name, :brand, :size, :date_of_purchase)
    end
end
  

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home ; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/garments_helper.rb
module GarmentsHelper
end

app/views/garments/index.html.erb
<h1>Garments</h1>

<% @garments.each do |garment| %>
  <div>
    <h2><%= garment.name %></h2>
    <p><strong>Brand:</strong> <%= garment.brand %></p>
    <p><strong>Size:</strong> <%= garment.size %></p>
    <p><strong>Date of Purchase:</strong> <%= garment.date_of_purchase %></p>
  </div>
  <hr>
<% end %>

<%= link_to 'New Garment', new_garment_path %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <% if user_signed_in?%>
          <li class="nav-item">
            <%= button_to "Logout", destroy_user_session_path, method: :delete, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Register", new_user_registration_path, class: "nav-link" %>
          </li>
        <% end %>

      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MisteryApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render partial: 'layouts/navbar' %>
    <div class="container">
    <%= yield %>
    </div>
  </body>
</html>

app/views/static_pages/home.html.erb
<h1>Bienvenido</h1>